spring.application.name=music-analyser-api

# Connexion Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/music_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Idem : on utilise une variable DB_HOST_CH
clickhouse.url=jdbc:clickhouse://${DB_HOST_CH:localhost}:8123/default?user=${DB_USER}&password=${DB_PASSWORD}

# --- Monitoring (OpenTelemetry & Micrometer) ---
# Ici, on rend l'URL dynamique. 
# Dans Docker, on injectera 'http://grafana:4318/...'
management.otlp.metrics.export.url=${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:4318/v1/logs}

# --- Tracing (OpenTelemetry) ---
# L'URL des traces (dynamique)
management.opentelemetry.tracing.export.otlp.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}


# Le taux d'échantillonnage (1.0 = 100% des requêtes sont tracées)
management.tracing.sampling.probability=1.0

#Swagger
springdoc.swagger-ui.path=/docs